name: Deploy to Server

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        HOST: overfitting.mlx.institute
        USER: root
        PORT: 22
      run: |
        # Exit immediately if a command exits with a non-zero status.
        set -e
        # Install SSH client
        sudo apt-get install -y openssh-client
        # Write SSH key for GitHub Actions
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        # SSH into the server and run deployment commands
        ssh -o StrictHostKeyChecking=no -p $PORT $USER@$HOST -i private_key <<- EOT
          set -e  # This is also important to set inside the SSH command.
          cd /root/Workspace/language-detection
          git pull origin main
          docker stop flask_app || true
          docker rm flask_app || true
          docker build -t language_detection_flask_app .
          docker run -d --name flask_app -p 8080:3031 language_detection_flask_app
        EOT
